name: Build-Java
on:
  workflow_dispatch:
jobs:
  Checkout:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-11
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-v /var/jenkins_home:/var/jenkins_home"
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: checkout
      uses: actions/checkout@v4.1.0
  Build_with_Maven:
    name: Build with Maven
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-11
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-v /var/jenkins_home:/var/jenkins_home"
    needs: Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: mvn clean package
  Post-Build:
    if: always()
    name: Post Build
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-11
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-v /var/jenkins_home:/var/jenkins_home"
    needs:
    - Checkout
    - Build_with_Maven
    steps:
    - name: snapshot post build workflow status
      run: |-
        echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
        echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
      id: post_build
    - name: echo message
      run: echo Maven build failed!
      if: steps.post_build.outputs.failure == 'true'
    - name: echo message
      run: echo Maven build succeeded!
      if: steps.post_build.outputs.success == 'true'
    - name: clean workspace
      shell: bash
      run: rm -rf ${{ github.workspace }}/*
      if: always()
