name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # setup-gcp:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
          
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1

  #     - name: Terraform Init
  #       run: terraform init
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} 

  #     - name: Terraform Plan
  #       run: terraform plan -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  #     - name: Terraform Apply
  #       id: terraform-apply
  #       run: terraform apply -auto-approve -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  deploy-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: 'Configure kubectl to use gke-gcloud-auth-plugin'
        run: gcloud components install kubectl

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials gke-cluster --zone us-east1-b --project stalwartl-1667731032306

      - name: Deploy application to GKE
        run: kubectl apply -f deployment.yaml

  # destroy-resources:
  #   runs-on: ubuntu-latest
  #   needs: [setup-gcp, deploy-application]
  #   if: always()  # Ensures this job always runs
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1

  #     - name: Terraform Destroy
  #       run: terraform destroy -auto-approve -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
