name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  setup-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Google Cloud Credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcp-key.json"
      
      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
      
      - name: Configure gcloud to use project
        run: gcloud config set project stalwartl-1667731032306
        
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_APPLICATIONS_CREDENTIALS: "${HOME}/gcp-key.json"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_APPLICATIONS_CREDENTIALS: "${HOME}/gcp-key.json"
          
      - name: Fetch GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials gke-cluster --region us-east1-b --project stalwartl-1667731032306
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"
          
  deploy-application:
    runs-on: ubuntu-latest
    needs: setup-gcp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          
  integration-test:
    runs-on: ubuntu-latest
    needs: deploy-application
    steps:
      - name: Run Integration Tests
        run: |
          newman run postman_collection.json

  cleanup:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Cleanup Kubernetes Deployment
        run: kubectl delete -f deployment.yaml

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        env:
          GOOGLE_APPLICATIONS_CREDENTIALS: "${HOME}/gcp-key.json"
