name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  setup-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} 

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  deploy-application:
    runs-on: ubuntu-latest
    needs: setup-gcp
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: stalwartl-1667731032306
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup kubectl
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials gke-cluster --region us-east1-b --project stalwartl-1667731032306

      - name: Deploy application to GKE
        run: kubectl apply -f deployment.yaml

  # destroy-resources:
  #   runs-on: ubuntu-latest
  #   needs: [setup-gcp, deploy-application]
  #   if: always()  # Ensures this job always runs
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1

  #     - name: Terraform Destroy
  #       run: terraform destroy -auto-approve -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
