name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

  cache:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Cache SonarQube packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  jacoco:
    runs-on: self-hosted
    needs: cache
    steps:
      - name: Build with Maven
        run: mvn -B package -Pcoverage
      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: jacoco-report
          path: target/site/jacoco/

  sonarqube:
    runs-on: self-hosted
    needs: jacoco
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Install Maven
        run: |
          if ! command -v mvn &> /dev/null; then
            echo "Maven not found. Installing Maven..."
            sudo apt update
            sudo apt install -y maven
          else
            echo "Maven is already installed."
          fi

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=todoapp -Dsonar.projectName='todoapp'

  artifacts:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: Prepare staging directory
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/*.jar  # Upload only the JAR file

  docker_build:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn -B package

      - name: Build Docker image
        run: docker build -t padmanabhan1/todoapp:1.0 .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push padmanabhan1/todoapp:1.0

  release:
    runs-on: ubuntu-latest
    needs: artifacts
    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v4.1.8
        with:
          name: Package
          
      - name: View JAR content
        run: ls -R

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_type }}
          release_name: Release ${{ github.ref_type }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./staging/*.jar  # Only the JAR file
          asset_name: app-v${{ github.ref_type }}.jar
          asset_content_type: application/java-archive
